Repository UnBArqDsw2021-1/2021.1_G01_Animalesco_docs, pull requests merged in 2021-08, with the labels that each got.

#31 Add 5W2H document
  docs/_sidebar.md
  docs/pages/5W2H.md
Labels: documentation

#53 Add questionnaire document
  .vscode/extensions.json
  docs/_sidebar.md
  docs/assets/pages/questionario/fluxo_do_questionario.png
  docs/assets/pages/questionario/pergunta1.png
  docs/assets/pages/questionario/pergunta10.png
  docs/assets/pages/questionario/pergunta11.png
  docs/assets/pages/questionario/pergunta12.png
  docs/assets/pages/questionario/pergunta13.png
  docs/assets/pages/questionario/pergunta14.png
  docs/assets/pages/questionario/pergunta15.png
  docs/assets/pages/questionario/pergunta16.png
  docs/assets/pages/questionario/pergunta2.png
  docs/assets/pages/questionario/pergunta3.png
  docs/assets/pages/questionario/pergunta4.png
  docs/assets/pages/questionario/pergunta5.png
  docs/assets/pages/questionario/pergunta6.png
  docs/assets/pages/questionario/pergunta7.png
  docs/assets/pages/questionario/pergunta8.png
  docs/assets/pages/questionario/pergunta9.png
  docs/pages/questionario.md
Labels: documentation

#54 Baseline de Requisitos
  docs/_sidebar.md
  docs/pages/backlog-do-produto.md
Labels: documentation

#76 63 - Diagrama de Sequência
  docs/_sidebar.md
  docs/assets/pages/sequence-diagram/sequence-diagram.png
  docs/pages/diagrama-de-sequencia.md
Labels: sprint 3, waiting for review

#73 Add most import templates
  .github/ISSUE_TEMPLATE/issue_template_meeting.md
  .github/ISSUE_TEMPLATE/issue_template_sprint_documentation.md
  .github/ISSUE_TEMPLATE/template-bug_report.md
  .github/ISSUE_TEMPLATE/template-default-issue.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: waiting for review

#75 67 - Diagrama de Estados
  docs/_sidebar.md
  docs/assets/pages/state-diagram/Diagrama_de_Estados_de_Banhos_de_Pet.jpeg
  docs/assets/pages/state-diagram/Diagrama_de_Estados_de_Cadastro_de_Pets.jpeg
  docs/assets/pages/state-diagram/Diagrama_de_Estados_de_Medicamentos_de_Pet.jpeg
  docs/assets/pages/state-diagram/Diagrama_de_Estados_de_Perfil.jpeg
  docs/assets/pages/state-diagram/Diagrama_de_Estados_de_Vacinas_de_Pet.jpeg
  docs/assets/pages/state-diagram/Diagrama_de_Estados_de_Visitas_ao_Veterinário.jpeg
  docs/pages/state-diagram.md
Labels: sprint 3, waiting for review

#74 #62 Add component diagram document
  docs/_sidebar.md
  docs/assets/pages/component-diagram/diagrama-de-componentes.jpg
  docs/pages/component-diagram.md
Labels: waiting for review

#81 64 communication diagram
  docs/_sidebar.md
  docs/assets/pages/communication-diagram/createPet.png
  docs/assets/pages/communication-diagram/frame.png
  docs/assets/pages/communication-diagram/lifeline.png
  docs/assets/pages/communication-diagram/message.png
  docs/assets/pages/communication-diagram/pet.png
  docs/pages/communication-diagram.md
  docs/pages/diagrama-de-sequencia.md
Labels: waiting for review

#92 Diagrama de caso de uso
  docs/assets/pages/use-case/use_case_diagram.png
  docs/pages/casos-de-uso/UC01.md
  docs/pages/casos-de-uso/UC02.md
  docs/pages/casos-de-uso/UC03.md
  docs/pages/casos-de-uso/UC04.md
  docs/pages/casos-de-uso/UC05.md
  docs/pages/casos-de-uso/UC06.md
  docs/pages/casos-de-uso/UC07.md
  docs/pages/casos-de-uso/UC08.md
  docs/pages/casos-de-uso/UC09.md
  docs/pages/casos-de-uso/UC10.md
  docs/pages/casos-de-uso/UC11.md
  docs/pages/casos-de-uso/UC12.md
  docs/pages/diagrama-de-caso-de-uso.md
Labels: waiting for review, sprint 4
